name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            USING_COVERAGE: "3.8"

        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9, "3.10"]

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v2
              with:
                  python-version: "${{ matrix.python-version }}"

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install black coverage coveragepy-lcov cvxopt cvxpy ecos flake8 flit mccabe mypy numpy osqp pylint pytest quadprog tox tox-gh-actions

            - name: "Run tox targets for ${{ matrix.python-version }}"
              run: |
                  tox -e py

            - name: "Convert coverage report to LCOV"
              run: |
                  coveragepy-lcov

            - name: "Coveralls"
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: "lcov.info"
